/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

import { useAppStore } from '@/stores/app-store';

// Define GLTF result type with dynamic records for nodes and materials
type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.Material>;
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const gltf = useGLTF('/models/hoodie-final-c.glb') as unknown as GLTFResult;
  const { nodes, materials } = gltf;

  const { hoodie } = useAppStore((state) => state); 

  console.log(hoodie);

  return (
    <group {...props} dispose={null}>
      <group name="back body" position={[0, -1.204, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_1_7_0_Inside.geometry}
          material={hoodie.torso.back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_1_7_0_Inside_1.geometry}
          material={hoodie.torso.back}
        />
      </group>
      <group name="Bottom Band.002" position={[0, -1.204, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_8_4_0_Inside.geometry}
          material={hoodie.torso.band}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_8_4_0_Inside_1.geometry}
          material={hoodie.torso.band}
        />
      </group>
      <group name="Front Body" position={[0, -1.204, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_0_6_0_Outside001.geometry}
          material={hoodie.torso.front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_0_6_0_Outside001_1.geometry}
          material={hoodie.torso.front}
        />
      </group>
      <group name="Left Sleeve" position={[0, -1.204, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_2_0_0_Inside.geometry}
          material={hoodie.arms.left.sleeve}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_2_0_0_Inside_1.geometry}
          material={hoodie.arms.left.sleeve}
        />
      </group>
      <group name="Right Sleeve" position={[0, -1.204, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_2_1_0_Outside001.geometry}
          material={hoodie.arms.right.sleeve}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_2_1_0_Outside001_1.geometry}
          material={hoodie.arms.right.sleeve}
        />
      </group>
      <group name="Left Cuff" position={[0, -1.204, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_4_2_0_Outside001.geometry}
          material={hoodie.arms.left.cuff}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_4_2_0_Outside001_1.geometry}
          material={hoodie.arms.left.cuff}
        />
      </group>
      <group name="Right Cuff" position={[0, -1.204, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_4_3_0_Outside001.geometry}
          material={hoodie.arms.right.cuff}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_4_3_0_Outside001_1.geometry}
          material={hoodie.arms.right.cuff}
        />
      </group>
      <group name="Design_Piece_mat_Shape 6_11_0_Inside" position={[0, -1.204, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_6_11_0_Inside_1.geometry}
          material={hoodie.hood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_6_11_0_Inside_2.geometry}
          material={hoodie.hood}
        />
      </group>
      <group  name="Design_Piece_mat_Shape 7_10_0_Outside"position={[0, -1.204, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_7_10_0_Outside001.geometry}
          material={hoodie.torso.pocket}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Design_Piece_mat_Shape_7_10_0_Outside001_1.geometry}
          material={hoodie.torso.pocket}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/hoodie-final-c.glb')